"""CLI tests for `gitsummary init github-release-notes`."""

from __future__ import annotations

from pathlib import Path

import pytest
import typer

from gitsummary.cli.commands import init as init_cmd


def test_init_writes_workflow_and_release_notes_readme(tmp_path: Path, monkeypatch) -> None:
    repo_root = tmp_path / "demo"
    repo_root.mkdir()

    monkeypatch.setattr(init_cmd, "repository_root", lambda: repo_root)
    monkeypatch.setenv("OPENAI_API_KEY", "sk-test")

    init_cmd.github_release_notes(
        yes=True,
        force=False,
        workflow_path=None,
        openai_key_env="OPENAI_API_KEY",
    )

    workflow_path = repo_root / ".github/workflows/gitsummary-release-notes.yml"
    assert workflow_path.exists()
    workflow = workflow_path.read_text(encoding="utf-8")
    assert "on:" in workflow
    assert "release:" in workflow
    assert "OPENAI_API_KEY" in workflow
    assert "gh release edit" in workflow

    readme_path = repo_root / "release-notes/README.md"
    assert readme_path.exists()
    readme = readme_path.read_text(encoding="utf-8")
    assert "This directory contains release notes generated by **gitsummary**." in readme


def test_init_refuses_overwrite_in_yes_mode_without_force(tmp_path: Path, monkeypatch) -> None:
    repo_root = tmp_path / "demo"
    repo_root.mkdir()

    monkeypatch.setattr(init_cmd, "repository_root", lambda: repo_root)
    monkeypatch.setenv("OPENAI_API_KEY", "sk-test")

    init_cmd.github_release_notes(yes=True, force=False, openai_key_env="OPENAI_API_KEY")

    with pytest.raises(typer.Exit) as exc:
        init_cmd.github_release_notes(yes=True, force=False, openai_key_env="OPENAI_API_KEY")
    assert exc.value.exit_code == 2

    # Overwrite is allowed with --force
    init_cmd.github_release_notes(yes=True, force=True, openai_key_env="OPENAI_API_KEY")


def test_init_yes_mode_requires_openai_key(tmp_path: Path, monkeypatch) -> None:
    repo_root = tmp_path / "demo"
    repo_root.mkdir()

    monkeypatch.setattr(init_cmd, "repository_root", lambda: repo_root)
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)

    class DummyConfigManager:
        def get_api_key(self, provider: str, prompt_if_missing: bool = False):
            return None

    monkeypatch.setattr(init_cmd, "get_config_manager", lambda: DummyConfigManager())

    with pytest.raises(typer.Exit) as exc:
        init_cmd.github_release_notes(yes=True, force=False, openai_key_env="OPENAI_API_KEY")
    assert exc.value.exit_code == 2


