"""CommitArtifact schema definition.

The CommitArtifact is the central data model of gitsummary.
It represents the "semantic understanding" of a single commit,
extracted via heuristics or LLM analysis.

NOTE: While defined as a Pydantic model (JSON Schema-compatible),
artifacts are serialized to YAML for storage in Git Notes to
improve human readability.
"""

from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field

from .enums import ChangeCategory, ImpactScope


class TokenUsage(BaseModel):
    """Token usage information for an LLM call."""

    input: Optional[int] = Field(None, description="Input tokens used.")
    output: Optional[int] = Field(None, description="Output tokens used.")
    cached: Optional[int] = Field(None, description="Cached tokens used, if available.")


class InputMetrics(BaseModel):
    """Size and scope metrics for the analyzed input."""

    commit_message_chars: Optional[int] = Field(None)
    commit_message_lines: Optional[int] = Field(None)
    commit_message_tokens: Optional[int] = Field(None)
    diff_files: Optional[int] = Field(None)
    diff_insertions: Optional[int] = Field(None)
    diff_deletions: Optional[int] = Field(None)
    diff_total: Optional[int] = Field(None)
    diff_hunks: Optional[int] = Field(None)
    diff_chars: Optional[int] = Field(None)
    diff_lines: Optional[int] = Field(None)
    diff_tokens: Optional[int] = Field(None)


class QualitativeSignal(BaseModel):
    """A qualitative score with an explanation."""

    score: Optional[int] = Field(None, ge=0, le=10)
    explanation: Optional[str] = Field(None)


class QualitativeScores(BaseModel):
    """Qualitative assessment of a commit."""

    technical_difficulty: Optional[QualitativeSignal] = None
    creativity: Optional[QualitativeSignal] = None
    mental_load: Optional[QualitativeSignal] = None
    review_effort: Optional[QualitativeSignal] = None
    ambiguity: Optional[QualitativeSignal] = None


class AnalysisMeta(BaseModel):
    """Metadata about how the artifact was produced."""

    analysis_mode: Optional[Literal["llm", "heuristic", "hybrid"]] = None
    provider: Optional[str] = None
    model: Optional[str] = None
    prompt_version: Optional[str] = None
    analysis_timestamp: Optional[str] = None
    analysis_duration_ms: Optional[int] = None
    fallback_reason: Optional[str] = None
    token_usage: Optional[TokenUsage] = None
    input_metrics: Optional[InputMetrics] = None
    qualitative: Optional[QualitativeScores] = None


class CommitArtifact(BaseModel):
    """The semantic understanding of a single commit.

    This artifact is generated by analyzing the commit message and code diff.
    It captures the "real" intent of the change, beyond what the commit
    message may or may not convey.

    Attributes:
        commit_hash: The full SHA-1 hash of the commit.
        schema_version: The version of this artifact schema.
        intent_summary: A concise, one-sentence summary of what this commit
            *actually* does. Often clarifies or corrects the original message.
        category: The primary category of this change.
        behavior_before: Description of the system's behavior before this change.
        behavior_after: Description of the system's behavior after this change.
        impact_scope: The scope of the impact (public_api, internal, etc.).
        is_breaking: True if this change breaks backward compatibility.
        technical_highlights: Key technical decisions found in the diff.
    """

    # --- Identity ---
    commit_hash: str = Field(
        ...,
        description="The full SHA-1 hash of the commit.",
    )
    schema_version: str = Field(
        "0.2.0",
        description="The version of this artifact schema.",
    )

    # --- The "Real" Intent (AI Extracted) ---
    intent_summary: str = Field(
        ...,
        description=(
            "A concise, one-sentence summary of what this commit *actually* does. "
            "Often clarifies or corrects the original commit message. "
            "Example: 'Fixes a null pointer exception in the user login flow "
            "by adding a check for missing credentials.'"
        ),
    )

    category: ChangeCategory = Field(
        ...,
        description="The primary category of this change.",
    )

    # --- Behavior Change (Crucial for Before/After analysis) ---
    behavior_before: Optional[str] = Field(
        None,
        description=(
            "Description of the system's behavior *before* this change. "
            "Focus on the specific functionality being modified. "
            "Example: 'Commands approved by execpolicy would still run in "
            "the sandbox and fail if they needed write access.'"
        ),
    )

    behavior_after: Optional[str] = Field(
        None,
        description=(
            "Description of the system's behavior *after* this change. "
            "Contrast directly with 'behavior_before'. "
            "Example: 'Commands approved by execpolicy now bypass the sandbox "
            "entirely and execute with full permissions.'"
        ),
    )

    # --- Impact Analysis ---
    impact_scope: ImpactScope = Field(
        ...,
        description=(
            "The scope of the impact. One of: public_api, internal, "
            "dependency, config, docs, test, unknown."
        ),
    )

    is_breaking: bool = Field(
        False,
        description=(
            "True if this change breaks backward compatibility "
            "for users or API consumers."
        ),
    )

    # --- Implementation Details ---
    technical_highlights: List[str] = Field(
        default_factory=list,
        description=(
            "A list of key technical decisions or interesting implementation "
            "details found in the diff. Focus on *how* the problem was solved. "
            "Example: ['Introduced Stopwatch abstraction to pause timeouts', "
            "'Inlined sandbox check for performance']"
        ),
    )

    # --- Analysis Metadata ---
    analysis_meta: Optional[AnalysisMeta] = Field(
        None,
        description="Metadata about analysis provenance, inputs, and qualitative scores.",
    )
